# Elias Barbosa maintained docker-compose.yml file.
# Creates multiple Drupal web apps sharing the same MySQL database
# Usage: docker-compose up -d
version: '2'
services:
  drupal:
    build:
      context: ./setup/builds/drupal-apache
    image: drupal:8.2.3-apache
    volumes:
      - ./:/html
      - ./setup/scripts/php.ini:/usr/local/etc/php/php.ini
      - ./html/modules:/var/www/html/modules
      - ./html/profiles:/var/www/html/profiles
      - ./html/themes:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      # - /var/www/html/sites
      # - ./scripts/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
      - mysql
    ports:
      - "8081:80"
    links:
      - mysql
      - phpmyadmin
    restart: always
  mysql:
    build:
      context: ./setup/builds/mariadb
    image: mariadb
    ports:
        - '3307:3306'
    volumes:
      - ./database:/root/mysql
      - /var/lib/mysql
      - /usr/bin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    restart: always
  data:
    image: busybox
    stdin_open: true
    volumes:
      - ./html:/var/www/html
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - '8091:80'
    links:
      - mysql
    restart: always